### ISSUE TITLE
checkpoint cannot be loaded

### ISSUE THREAD

**Issue by Funaizhang** [weiyx16/Active-Perception#1]
The checkpoint file in DQN/dqn/checkpoint seems to be invalid. 
self.load_model() in agent_8.py returns the following error

``` 
[*] Loading checkpoints...
2019-07-23 16:57:57.724805: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key prediction/7_lq_1/biases not found in checkpoint
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key prediction/7_lq_1/biases not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

etc...
```

dqn_model_ckpt-13400.data-00000-of-00001 seems to contain the model data. However, my attempt to load this as checkpoint is unsuccessful too.

```
 [*] Loading checkpoints...
 [!] Load FAILED: ./dqn/checkpoint
 [*] Created model with fresh parameters.
```

**Comment by weiyx16** [comment]
Sorry, the checkpoint file we upload is for agent_18.py. Its structure is a little different from the one in agent_8.py, which cause the loading failure.
**Please use the agent_18.py as agent file**
